name: lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2
      - run: yarn install
      - run: echo "export const KITSPACE_PROCESSOR_API_KEY = 'fake_key'" > secrets.development.js
      - run: yarn lint --max-warnings 0
      - run: yarn tsc
      - run: NODE_ENV=production yarn build
      - run: yarn web-ext lint
