name: Lint, build and test

on:
  push:

jobs:
  lint-and-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2
      - run: yarn install
      - run: echo "export const KITSPACE_PROCESSOR_API_KEY = 'fake_key'" > secrets.production.js
      - run: yarn lint --max-warnings 0
      - run: yarn tsc
      - run: yarn build
      - run: yarn web-ext lint
      - run: xvfb-run --auto-servernum yarn test
