name: Lint and build

on:
  push:

jobs:
  lint-and-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2
      - run: 'yarn install'
      - run: 'yarn lint --max-warnings 0'
      - run: 'yarn build'
